from typing import Optional, List
import sqlite3
import time

from backend.domain.entities.Player import Player
from backend.domain.entities.Quizz import Quizz
from backend.domain.entities.Question import Question
from backend.domain.entities.FillInStatement import FillInStatement
from backend.domain.entities.Minigame import Minigame

from backend.repository.PlayerRepository import PlayerRepository
from backend.repository.QuizzRepository import QuizzRepository
from backend.repository.QuestionRepository import QuestionRepository
from backend.repository.FillInStatementRepository import FillInStatementRepository
from backend.repository.MinigameRepository import MinigameRepository
from backend.repository.QuizzTaskRepository import QuizzTaskRepository

from backend.service.PlayerService import PlayerService
from backend.service.QuizzService import QuizzService
from backend.service.QuestionService import QuestionService
from backend.service.FillInStatementService import FillInStatementService
from backend.service.MinigameService import MinigameService
from backend.service.QuizzTaskService import QuizzTaskService


class GameService:
    """
    Main game service that coordinates all game operations with a set player context.
    This service manages the overall game flow and interactions between different entities.
    """
    
    def __init__(self, conn: sqlite3.Connection):
        # Initialize repositories
        self.player_repository = PlayerRepository(conn)
        self.quizz_repository = QuizzRepository(conn)
        self.question_repository = QuestionRepository(conn)
        self.fill_in_repository = FillInStatementRepository(conn)
        self.minigame_repository = MinigameRepository(conn)
        self.quizz_task_repository = QuizzTaskRepository(conn)
        
        # Initialize services
        self.player_service = PlayerService(self.player_repository)
        self.quizz_service = QuizzService(self.quizz_repository)
        self.question_service = QuestionService(self.question_repository)
        self.fill_in_service = FillInStatementService(self.fill_in_repository)
        self.minigame_service = MinigameService(self.minigame_repository)
        self.quizz_task_service = QuizzTaskService(self.quizz_task_repository)
        
        # Current player context
        self.__current_player: Optional[Player] = None
        
        # Progress tracking for current quizz session
        self.__current_quizz: Optional[Quizz] = None
        self.__completed_tasks: set = set()  # Set of completed task IDs
        self.__task_results: dict = {}  # Dict of task_id -> result details
        self.__session_start_time: Optional[float] = None
    
    # Player Management
    def set_player(self, player: Player) -> None:
        """Set the current player context."""
        self.__current_player = player
    
    def get_current_player(self) -> Optional[Player]:
        """Get the current player."""
        return self.__current_player
    
    def load_player(self) -> bool:
        """Load the player from repository and set as current."""
        player = self.player_service.get_player()
        if player:
            self.__current_player = player
            return True
        return False
    
    def create_and_set_player(self, name: str) -> Player:
        """Create a new player and set as current. ID is auto-generated by database."""
        player = self.player_service.create_player(name)
        self.__current_player = player
        return player
    
    def ensure_player(self) -> Player:
        """Ensure a player is set, raise error if not."""
        if self.__current_player is None:
            raise ValueError("No player is currently set. Please set a player first.")
        return self.__current_player
    
    def login(self, username: str, auto_create: bool = True) -> dict:
        """
        Login a player by username (unique identifier).
        
        Args:
            username: The unique username of the player
            auto_create: If True, creates a new player if username doesn't exist
        
        Returns:
            dict with 'success' (bool), 'player' (Player or None), 'message' (str), 'is_new' (bool)
        """
        # Try to find existing player
        player = self.player_service.get_player_by_name(username)
        
        if player:
            # Player exists, set as current
            self.__current_player = player
            return {
                "success": True,
                "player": player,
                "message": f"Welcome back, {username}!",
                "is_new": False
            }
        
        # Player doesn't exist
        if auto_create:
            # Create new player (ID will be auto-generated by database)
            player = self.player_service.create_player(username)
            self.__current_player = player
            
            return {
                "success": True,
                "player": player,
                "message": f"Welcome, {username}! Your account has been created.",
                "is_new": True
            }
        else:
            return {
                "success": False,
                "player": None,
                "message": f"No player found with username '{username}'.",
                "is_new": False
            }
    
    # Player Operations
    def add_credits_to_player(self, amount: int) -> None:
        """Add credits to the current player."""
        player = self.ensure_player()
        self.player_service.add_credits(player, amount)
    
    def purchase_cosmetic(self, cosmetic: str, price: int) -> bool:
        """Purchase a cosmetic for the current player."""
        player = self.ensure_player()
        return self.player_service.purchase_cosmetic(player, cosmetic, price)
    
    def unlock_region(self, region: str) -> None:
        """Unlock a region for the current player."""
        player = self.ensure_player()
        self.player_service.unlock_region(player, region)
    
    def equip_cosmetic(self, cosmetic: str) -> bool:
        """Equip a cosmetic for the current player."""
        player = self.ensure_player()
        return self.player_service.equip_cosmetic(player, cosmetic)
    
    # Quizz Operations
    def start_quizz(self, quizz_id: int) -> Optional[Quizz]:
        """Start a quizz for the current player and initialize progress tracking."""
        player = self.ensure_player()
        quizz = self.quizz_service.get_quizz_by_id(quizz_id)
        
        if quizz:
            # Initialize progress tracking
            self.__current_quizz = quizz
            self.__completed_tasks = set()
            self.__task_results = {}
            self.__session_start_time = time.time()
        
        return quizz
    
    def get_current_quizz(self) -> Optional[Quizz]:
        """Get the currently active quizz."""
        return self.__current_quizz
    
    def complete_quizz(self, quizz: Optional[Quizz] = None, credits_earned: int = 0) -> dict:
        """
        Complete a quizz and update player statistics.
        
        Args:
            quizz: The completed quizz (uses current quizz if None)
            credits_earned: Credits earned from completing the quizz
        
        Returns:
            dict with completion summary
        """
        player = self.ensure_player()
        target_quizz = quizz or self.__current_quizz
        
        if not target_quizz:
            raise ValueError("No quizz to complete. Start a quizz first.")
        
        # Calculate play time
        play_time = time.time() - self.__session_start_time if self.__session_start_time else 0.0
        
        # Calculate if quizz is solved based on current progress
        progress = self.get_quizz_progress()
        is_solved = progress["completion_percentage"] >= 100.0
        
        # Update quizz completion
        if is_solved:
            target_quizz.set_completion_percentage(100.0)
            self.quizz_service.update_quizz(target_quizz)
        else:
            target_quizz.set_completion_percentage(progress["completion_percentage"])
            self.quizz_service.update_quizz(target_quizz)
        
        # Update player statistics
        self.player_service.update_quizz_statistics(player, is_solved, play_time)
        
        # Award credits if earned
        if credits_earned > 0:
            self.player_service.add_credits(player, credits_earned)
        
        # Create completion summary
        completion_summary = {
            "quizz_id": target_quizz.get_id(),
            "is_solved": is_solved,
            "completion_percentage": progress["completion_percentage"],
            "tasks_completed": len(self.__completed_tasks),
            "total_tasks": progress["total_tasks"],
            "play_time": round(play_time, 2),
            "credits_earned": credits_earned,
            "breakdown": progress["breakdown"],
            "results": self.__task_results
        }
        
        # Clear current quizz session
        self.__current_quizz = None
        self.__completed_tasks = set()
        self.__task_results = {}
        self.__session_start_time = None
        
        return completion_summary
    
    def update_quizz_progress(self, quizz: Quizz, completed_tasks: int) -> None:
        """Update the progress of a quizz based on completed tasks."""
        percentage = self.quizz_service.calculate_completion_percentage(quizz, completed_tasks)
        self.quizz_service.update_completion_percentage(quizz, percentage)
    
    def get_quizzes_by_difficulty(self, difficulty: str) -> List[Quizz]:
        """Get all quizzes with a specific difficulty."""
        return self.quizz_service.get_quizzes_by_difficulty(difficulty)
    
    # Question Operations
    def answer_question(self, question: Question, user_answers: List[str]) -> dict:
        """
        Answer a question, track progress, and return the result.
        
        Returns:
            dict with 'correct' (bool), 'correct_answers' (list), and 'is_multiple_choice' (bool)
        """
        is_correct = self.question_service.check_answer(question, user_answers)
        
        result = {
            "task_id": question._id,
            "task_type": "question",
            "correct": is_correct,
            "correct_answers": self.question_service.get_correct_answers(question),
            "is_multiple_choice": self.question_service.is_multiple_choice(question),
            "user_answers": user_answers
        }
        
        # Track progress
        if is_correct:
            self.__completed_tasks.add(question._id)
        self.__task_results[question._id] = result
        
        # Auto-update quizz progress if current quizz is set
        if self.__current_quizz:
            self.update_quizz_progress(self.__current_quizz, len(self.__completed_tasks))
        
        return result
    
    def get_questions_for_quizz(self, quizz: Quizz) -> List[Question]:
        """Get all questions for a quizz."""
        return quizz.get_questions()
    
    # Fill-in Statement Operations
    def answer_fill_in(self, statement: FillInStatement, user_answers: List[str]) -> dict:
        """
        Answer a fill-in statement, track progress, and return detailed results.
        
        Returns:
            dict with 'correct' (bool), 'total', 'correct_count', and 'details'
        """
        results = self.fill_in_service.check_partial_answers(statement, user_answers)
        is_correct = results["correct"] == results["total"]
        
        result = {
            "task_id": statement._id,
            "task_type": "fill_in",
            "correct": is_correct,
            "total": results["total"],
            "correct_count": results["correct"],
            "details": results["details"],
            "user_answers": user_answers
        }
        
        # Track progress
        if is_correct:
            self.__completed_tasks.add(statement._id)
        self.__task_results[statement._id] = result
        
        # Auto-update quizz progress if current quizz is set
        if self.__current_quizz:
            self.update_quizz_progress(self.__current_quizz, len(self.__completed_tasks))
        
        return result
    
    def get_fill_in_preview(self, statement: FillInStatement) -> str:
        """Get a preview of a fill-in statement with blanks."""
        return self.fill_in_service.get_statement_preview(statement)
    
    def get_fill_ins_for_quizz(self, quizz: Quizz) -> List[FillInStatement]:
        """Get all fill-in statements for a quizz."""
        return quizz.get_fill_in_statements()
    
    # Minigame Operations
    def play_minigame(self, minigame: Minigame) -> dict:
        """
        Get minigame info for playing.
        
        Returns:
            dict with 'type', 'win_configuration', and type-specific data
        """
        minigame_type = self.minigame_service.get_minigame_type(minigame)
        
        result = {
            "type": minigame_type,
            "win_configuration": minigame.get_win_configuration()
        }
        
        # Add type-specific data
        if minigame_type == "puzzle":
            result["image_path"] = self.minigame_service.get_puzzle_image_path(minigame)
        elif minigame_type == "rebus":
            result["questions"] = self.minigame_service.get_rebus_questions(minigame)
        elif minigame_type == "pairs":
            result["items"] = self.minigame_service.get_pairs_items(minigame)
        
        return result
    
    def check_minigame_completion(self, minigame: Minigame) -> dict:
        """
        Check if a minigame is completed correctly and track progress.
        
        Returns:
            dict with 'completed' (bool) and 'task_id'
        """
        is_completed = self.minigame_service.check_win_condition(minigame)
        
        result = {
            "task_id": minigame.get_id(),
            "task_type": "minigame",
            "completed": is_completed,
            "minigame_type": self.minigame_service.get_minigame_type(minigame)
        }
        
        # Track progress
        if is_completed:
            self.__completed_tasks.add(minigame.get_id())
        self.__task_results[minigame.get_id()] = result
        
        # Auto-update quizz progress if current quizz is set
        if self.__current_quizz:
            self.update_quizz_progress(self.__current_quizz, len(self.__completed_tasks))
        
        return result
    
    def get_minigames_for_quizz(self, quizz: Quizz) -> List[Minigame]:
        """Get all minigames for a quizz."""
        return quizz.get_minigames()
    
    # Progress Monitoring
    def get_quizz_progress(self, quizz: Optional[Quizz] = None) -> dict:
        """
        Get detailed progress for a quizz.
        
        Args:
            quizz: The quizz to check progress for. If None, uses current quizz.
        
        Returns:
            dict with detailed progress information
        """
        target_quizz = quizz or self.__current_quizz
        
        if not target_quizz:
            return {
                "error": "No quizz specified and no current quizz active",
                "completion_percentage": 0.0
            }
        
        total_questions = len(target_quizz.get_questions())
        total_fill_ins = len(target_quizz.get_fill_in_statements())
        total_minigames = len(target_quizz.get_minigames())
        total_tasks = total_questions + total_fill_ins + total_minigames
        
        completed_count = len(self.__completed_tasks)
        completion_percentage = (completed_count / total_tasks * 100) if total_tasks > 0 else 0.0
        
        return {
            "quizz_id": target_quizz.get_id(),
            "difficulty": target_quizz.get_difficulty(),
            "total_tasks": total_tasks,
            "completed_tasks": completed_count,
            "remaining_tasks": total_tasks - completed_count,
            "completion_percentage": round(completion_percentage, 2),
            "breakdown": {
                "questions": {
                    "total": total_questions,
                    "completed": sum(1 for task_id in self.__completed_tasks 
                                   if any(q._id == task_id for q in target_quizz.get_questions()))
                },
                "fill_ins": {
                    "total": total_fill_ins,
                    "completed": sum(1 for task_id in self.__completed_tasks 
                                   if any(f._id == task_id for f in target_quizz.get_fill_in_statements()))
                },
                "minigames": {
                    "total": total_minigames,
                    "completed": sum(1 for task_id in self.__completed_tasks 
                                   if any(m.get_id() == task_id for m in target_quizz.get_minigames()))
                }
            },
            "task_results": self.__task_results
        }
    
    def get_task_result(self, task_id: int) -> Optional[dict]:
        """Get the result of a specific task."""
        return self.__task_results.get(task_id)
    
    def is_task_completed(self, task_id: int) -> bool:
        """Check if a specific task has been completed."""
        return task_id in self.__completed_tasks
    
    def reset_quizz_progress(self) -> None:
        """Reset the current quizz progress tracking."""
        self.__completed_tasks = set()
        self.__task_results = {}
        self.__session_start_time = None
    
    def get_completed_tasks_ids(self) -> List[int]:
        """Get list of all completed task IDs in current session."""
        return list(self.__completed_tasks)
    
    def get_session_duration(self) -> float:
        """Get the current session duration in seconds."""
        if self.__session_start_time:
            return time.time() - self.__session_start_time
        return 0.0
    
    # Overall Game Statistics
    def get_player_statistics(self) -> dict:
        """Get comprehensive statistics for the current player."""
        player = self.ensure_player()
        
        return {
            "player_name": player.get_name(),
            "credits": player.get_credits(),
            "avg_play_time": player.get_avg_play_time(),
            "quizzes_solved": player.get_quizzes_solved(),
            "quizzes_played": player.get_quizzes_played(),
            "regions_unlocked": player.get_regions_unlocked(),
            "completion_percentage": player.get_completion_percentage(),
            "cosmetics_unlocked": len(player.get_cosmetics_unlocked()),
            "cosmetics_purchased": len(player.get_cosmetics_purchased())
        }
    
    def get_game_progress(self) -> dict:
        """Get overall game progress for the current player."""
        player = self.ensure_player()
        task_stats = self.quizz_task_service.get_task_statistics()
        
        return {
            "player": {
                "name": player.get_name(),
                "credits": player.get_credits(),
                "completion_percentage": player.get_completion_percentage()
            },
            "tasks": task_stats,
            "regions_unlocked": len(player.get_regions_unlocked()),
            "quizzes_stats": {
                "solved": player.get_quizzes_solved(),
                "played": player.get_quizzes_played(),
                "success_rate": (player.get_quizzes_solved() / player.get_quizzes_played() * 100) 
                               if player.get_quizzes_played() > 0 else 0.0
            }
        }
    
    def calculate_and_update_overall_completion(self) -> float:
        """Calculate and update the player's overall game completion percentage."""
        player = self.ensure_player()
        
        # This is a simplified calculation - adjust based on your game logic
        # You might want to factor in: regions unlocked, quizzes completed, etc.
        total_regions = 10  # Adjust based on your game
        regions_unlocked = len(player.get_regions_unlocked())
        
        completion = (regions_unlocked / total_regions) * 100
        self.player_service.update_completion_percentage(player, completion)
        
        return completion
